name: Publish Extension

on:
  push:
    branches:
      - main
    paths:
      - extension/**

jobs:
  deploy_extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./extension

      - name: Check if tag for this version already exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: check-tag
        with:
          tag: "v${{ steps.package-version.outputs.current-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use node modules from cache if available
        uses: ./.github/actions/custom-actions/cache-node-modules

      - name: Install dependencies
        run: |-
          yarn

      - name: Create env.ts file
        working-directory: ./extension
        run: |-
          echo 'export const API_BASE_URL = "https://vscode-bugsnag-stepthrough.vercel.app";' > src/env.ts

      - name: Run tests and linter
        working-directory: ./extension
        run: |-
          yarn lint --quiet
          yarn typecheck

      - name: Publish extension to marketplace
        if: ${{ steps.check-tag.outputs.exists == 'false' }}
        working-directory: ./extension
        run: |-
          yarn release
        env:
          API_BASE_URL: https://vscode-bugsnag-stepthrough.vercel.app
          VSCE_PAT: ${{ secrets.AZURE_ACCESS_TOKEN }}

      - name: Create tag for version
        if: ${{ steps.check-tag.outputs.exists == 'false' }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ steps.package-version.outputs.current-version }}"
          message: "Release v${{ steps.package-version.outputs.current-version }}"
