name: Run PR Checks

on: "pull_request"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Use node modules from cache if available
        uses: ./.github/actions/custom-actions/cache-node-modules

      - name: Install dependencies
        run: |-
          yarn

      - name: Run tests and linter in components dir
        working-directory: ./components
        run: |-
          yarn lint --quiet
          yarn typecheck

      - name: Create env.ts file
        working-directory: ./extension
        run: |-
          echo 'export const API_BASE_URL = "http://localhost:3000";' > src/env.ts

      - name: Run tests and linter in extension dir
        working-directory: ./extension
        run: |-
          yarn lint --quiet
          yarn typecheck

      - name: Run tests and linter in website dir
        working-directory: ./website
        run: |-
          yarn lint --quiet
          yarn typecheck
