name: Deploy Website

on:
  push:
    branches:
      - fix/vercel-yarn-workspaces
    # paths:
    #   - website/**
    #   - components/**

jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout GitHub Actions Repo
        uses: actions/checkout@v2
        with:
          repository: julianburr/github-actions
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .github/actions/custom-actions

      - name: Use node modules from cache if available
        uses: ./.github/actions/custom-actions/cache-node-modules

      - name: Install dependencies
        run: |-
          yarn

      - name: Linting and typechecks
        working-directory: ./website
        run: |-
          yarn lint
          yarn typecheck

      - name: Create .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS_ID }}

      - name: Run build
        working-directory: ./website
        run: |-
          yarn build

      - name: Deploy via Vercel
        uses: ./.github/actions/custom-actions/deploy-vercel
        with:
          working-directory: ./website
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN}}
          is-production: true
          add-comment: false
